name: Deploy vm-linux

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checar código
        uses: actions/checkout@v3

      - name: Configurar ssh-agent com chave privada
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Fazer deploy na rede local
        run: |
          ssh joao@192.168.4.40 <<'EOF'
          echo "INICIANDO DEPLOY"
          cd /home/joao/service-termografia
          git pull
          pnpm install --frozen-lockfile --reporter=append-only
          pnpm prisma db pull
          pnpm prisma generate
          pm2 restart termo-service
          echo "DEPLOY CONCLUÍDO"
          EOF

